### ISSUE TITLE
DLL (.pyd) file cannot be loaded on Windows or Linux

### ISSUE THREAD

**Issue by AnimeshSinha1309** [BensonZhou1991/Circuit-Transformation-via-Monte-Carlo-Tree-Search#1]
Why I try to run the code, the following error pops up:
![image](https://user-images.githubusercontent.com/9739218/93010590-d9c4fd80-f5ab-11ea-87f0-d7bfd73a2c0b.png)

The `to_python` file in the `C` module has the following statement which causes the error:
```python
__file__ = pkg_resources.resource_filename(__name__, 'to_python.cp37-win_amd64.pyd')
```
This is a Windows file so it does not have the appropriate ELF header for Ubuntu.

If compatibility with only Windows is intended, please add that to the requirements or README. Otherwise please provide a alternative for Ubuntu or let us know if we can help do that.

**Comment by AnimeshSinha1309** [comment]
![Windows Error snapshot](https://user-images.githubusercontent.com/9739218/93012399-b440ef80-f5bd-11ea-9b8e-7077ed395d1c.png)

The error message on windows is: `ImportError: DLL load failed while importing to_python: The specified module could not be found.`
The same problem occurs with Windows too, so I don't know if there is a greater issue or I am doing something wrong.

**Comment by AnimeshSinha1309** [comment]
For that matter I cannot find the C code which has the SimTest function so that I can start using this framework and replicating the results. Please help.

**Comment by BensonZhou1991** [comment]
Thanks for your comment. Our program is currently compatible only to Windows and we will add it to README.

When running in my computer, everything is fine, but when I try to run it on another windows laptop the same error message appears. I am trying to work it out and will contact you as soon as it is fixed.

Thanks again for your comment.

**Comment by BensonZhou1991** [comment]
Is your Python version 3.8? I find that our program seems not compatible with Python 3.8, and we should use Python 3.7 instead.

**Comment by AnimeshSinha1309** [comment]
Yes, it is 3.8, I will switch to 3.7 and check. Can you please let me know where the C files are which compile to the `.pyd` file and implement the simtest function. Is the entire code opensource? What part of it is in C?

I will test on Python 3.7 and write back to you in a couple of hours.

**Comment by BensonZhou1991** [comment]
.pyd file is used to implement the Simulation function (the detailed algorithm is in our paper in arXiv) and the relevant source code isn't in this repository. If you want the source code of it, you can leave an e-mail here and I will send it to you later.

**Comment by AnimeshSinha1309** [comment]
Thanks a lot, the code is working with Python 3.7 on Windows.
My email is animesh.sinha@research.iiit.ac.in, I would love to have the complete code of the C++ segment, would make extensions a lot easier.
Thanks again.
